<a href="https://colab.research.google.com/github/MANOJKUMARKONDURU/3_NumPy_Oct_2025/blob/main/1_Numpy_Bascis_Oct1_2025/10_Splitting_Array_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Splitting Numpy Arrays
Spliting is reverse operation of joining

Joining merges multiple arrays into one and Spliting means breaks one array into multiple.

We use **array_split()** for splitting arrays, we pass it the array we want to split and the number of splits.


The return value is a list.

**If the array has less elements than required, it will adjust from the end accoringly**



In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5, 7])

arr = np.array_split(arr1, 2)
print(arr)

arr = np.array_split(arr1, 3)
print(arr)

arr = np.array_split(arr1, 4)
print(arr)


[array([1, 2, 3]), array([4, 5, 7])]
[array([1, 2]), array([3, 4]), array([5, 7])]
[array([1, 2]), array([3, 4]), array([5]), array([7])]


**Note**: We also have the method **split()** available but it will not adjust the elements when elements are less in source array for splitting like in example above, **array_split()** worked properly but **split()** would fail.



# Split into Arrays


Acess the splitted arrays

In [ ]:
arr = np.array_split(arr1, 3)
print(arr)

print(arr[0])
print(arr[1])
print(arr[2])

# 2-Array

arr2 = np.array([[1, 2, 3], [4, 5, 7], [8, 9, 10], [11, 12, 13], [2, 5, 7], [21, 27, 21]])
arr = np.array_split(arr2, 2)

print(arr)
print(arr[0])
arr = np.array_split(arr2, 3)
print(arr)

print(arr[0])

[array([1, 2]), array([3, 4]), array([5, 7])]
[1 2]
[3 4]
[5 7]
[array([[ 1,  2,  3],
       [ 4,  5,  7],
       [ 8,  9, 10]]), array([[11, 12, 13],
       [ 2,  5,  7],
       [21, 27, 21]])]
[[ 1  2  3]
 [ 4  5  7]
 [ 8  9 10]]
[array([[1, 2, 3],
       [4, 5, 7]]), array([[ 8,  9, 10],
       [11, 12, 13]]), array([[ 2,  5,  7],
       [21, 27, 21]])]
[[1 2 3]
 [4 5 7]]


#you can specify which axis you want to do the split around.

In [ ]:
arr = np.array_split(arr2, 2, axis = 1)
print(arr)

arr = np.array_split(arr2, 2, axis = 0)
print(arr)

[array([[ 1,  2],
       [ 4,  5],
       [ 8,  9],
       [11, 12],
       [ 2,  5],
       [21, 27]]), array([[ 3],
       [ 7],
       [10],
       [13],
       [ 7],
       [21]])]
[array([[ 1,  2,  3],
       [ 4,  5,  7],
       [ 8,  9, 10]]), array([[11, 12, 13],
       [ 2,  5,  7],
       [21, 27, 21]])]


#vsplit()
spilt arrays along rows

#hsplit()
spilt arrays along columns

#dsplit()
split arrays along depth-wise


In [ ]:
arr = np.hsplit(arr2, 3 )
print(arr)

arr = np.vsplit(arr2, 3)
print(arr)
print("dsplit")
arr3 = np.array([[[1, 2], [3, 4]], [[5, 7],[8, 9]] ])
arr = np.dsplit(arr3, 2)
print(arr)

[array([[ 1],
       [ 4],
       [ 8],
       [11],
       [ 2],
       [21]]), array([[ 2],
       [ 5],
       [ 9],
       [12],
       [ 5],
       [27]]), array([[ 3],
       [ 7],
       [10],
       [13],
       [ 7],
       [21]])]
[array([[1, 2, 3],
       [4, 5, 7]]), array([[ 8,  9, 10],
       [11, 12, 13]]), array([[ 2,  5,  7],
       [21, 27, 21]])]
dsplit
[array([[[1],
        [3]],

       [[5],
        [8]]]), array([[[2],
        [4]],

       [[7],
        [9]]])]
