<a href="https://colab.research.google.com/github/MANOJKUMARKONDURU/3_NumPy_Oct_2025/blob/main/1_Numpy_Bascis_Oct1_2025/4_Data_Types_NumPy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy Data Types




*  **s** - strings

*  **i** - integer

*   **f** - float
*   **b** - boolean

*   **c** - complex float - eg: 1.0 + 2.0j
*  **m** - timedelta

* **M** - Datetime
* **O** - Object
* **S** - String
* **U** - unicode string
* **V** - fixed chunk of memory for other type(void)

---
Checking data type of an Array

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3, 4])
string = np.array(['aaaaaaa', 'b', 'c'])
print(arr.dtype)
print(string.dtype)

int64
<U7


#Creating array with a Defined data type

In [ ]:
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


#For i , u, f, S, U we can define size as well

In [ ]:
arr = np.array([1, 2, 3, 5], dtype = 'i4')
print(arr)
print(arr.dtype)

[1 2 3 5]
int32


#Converting Data Type on Exsting Arrays
the best way to change the data type of an existing array, is to make a copy of the array with the **astype()** method

The **astype()** function creates a copy of the array and allows you to pass the data type as a parameter


In [ ]:
arr = np. array([0, 1, 2, 3.5 , 4.7])
integer = arr.astype("i")

decimals = arr.astype("f")
boolean = arr.astype(bool)

print(arr)
print(integer)
print(decimals)
print(boolean)
print(integer.dtype)
print(decimals.dtype)
print(boolean.dtype)

[0.  1.  2.  3.5 4.7]
[0 1 2 3 4]
[0.  1.  2.  3.5 4.7]
[False  True  True  True  True]
int32
float32
bool
