<a href="https://colab.research.google.com/github/MANOJKUMARKONDURU/3_NumPy_Oct_2025/blob/main/1_Numpy_Bascis_Oct1_2025/9_Joining_Array_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Joining NumPy Arrays

Means putting contents of two or more arrays together in a single array

We pass sequence of arrays that we wants to join to the **concatenate()** fuction along with axis, if we didn't mentioned the axis explicitly, it is taken 0

In [ ]:
import numpy as np

In [ ]:
first_arr = np.array([1, 2, 3])
second_arr = np.array([4, 5, 7])

concatenated_arr = np.concatenate((first_arr, second_arr))
print(concatenated_arr)

[1 2 3 4 5 7]


# 2D array with and without specified axis



1.   axis = 0 - joins vertically(along rows)
2.   axis = 1 - joins horizontally(along columns)
3.  axis = 2 - joins depth-wise(for 3D arrays)



In [ ]:
first_arr2 = np.array([[1, 2, 3], [4, 5, 7]])
second_arr2 = np.array([[8, 9, 10], [11, 12, 13]])
arr = np.concatenate((first_arr2, second_arr2), axis = 0) #with axis = 0
print(arr)
print()
arr2 = np.concatenate((first_arr2, second_arr2), axis = 1) # with axis = 1
print(arr2)


first_arr3 = np.array([[[1, 2, 3], [4, 5, 7]], [[8, 9, 10], [11, 12, 13]]])
second_arr3 = np.array([[[14, 15, 16], [17, 18, 19]], [[20, 21, 22], [23, 24, 25]]])

arr3 = np.concatenate((first_arr3, second_arr3), axis = 2) # with axis = 2
print("\n\n")
print(f"3D concatenated array: {arr3}")

[[ 1  2  3]
 [ 4  5  7]
 [ 8  9 10]
 [11 12 13]]

[[ 1  2  3  8  9 10]
 [ 4  5  7 11 12 13]]



3D concatenated array: [[[ 1  2  3 14 15 16]
  [ 4  5  7 17 18 19]]

 [[ 8  9 10 20 21 22]
  [11 12 13 23 24 25]]]


# Joining arrays using Stack functions
same as concatenate, the only difference is that **stacking is done along a new axis**

We can concatenate 1-D arrays along with the second axis which would result in putting them over the other, ie. stacking

We can pass the sequence of arrays that we want to join to the **stack()** functioin, along with the axis. If axis is not explicitly passed it is taken as 0



In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 7])

arr = np.stack((arr1, arr2), axis = 0)
print(arr)
print()
arr = np.stack((arr1, arr2), axis = 1)
print(arr)


# 2D array

arr_1 = np.array([[1, 2, 3], [4, 5, 7]])
arr_2 = np.array([[8, 9, 10], [11, 12, 13]])

arr = np.stack((arr_1, arr_2), axis = 0)
print("\n\n")
print(arr)

print()

arr = np.stack((arr_1, arr_2), axis = 1)
print(arr)

print()
arr = np.stack((arr_1, arr_2), axis = 2)
print(arr)

[[1 2 3]
 [4 5 7]]

[[1 4]
 [2 5]
 [3 7]]



[[[ 1  2  3]
  [ 4  5  7]]

 [[ 8  9 10]
  [11 12 13]]]

[[[ 1  2  3]
  [ 8  9 10]]

 [[ 4  5  7]
  [11 12 13]]]

[[[ 1  8]
  [ 2  9]
  [ 3 10]]

 [[ 4 11]
  [ 5 12]
  [ 7 13]]]


# Stacking Along Rows - **hstack()**
NumPy priovides a helper function - **hstack()** to stack along **rows**

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 7])

arr = np.hstack((arr1, arr2))
print(arr)
print()

# 2D array

arr_1 = np.array([[1, 2, 3], [4, 5, 7]])
arr_2 = np.array([[8, 9, 10], [11, 12, 13]])


arr = np.hstack((arr_1, arr_2))
print(arr)

[1 2 3 4 5 7]

[[ 1  2  3  8  9 10]
 [ 4  5  7 11 12 13]]


# Stacking along Columns
NumPy provides a helper function: **vstack()** to stack along **columns**

In [ ]:
arr = np.vstack((arr1, arr2))
print(arr)

print()

arr = np.vstack((arr_1, arr_2))
print(arr)

[[1 2 3]
 [4 5 7]]

[[ 1  2  3]
 [ 4  5  7]
 [ 8  9 10]
 [11 12 13]]


# Stacking along Height(depth)
NumPy provides a helper function: **dstack()**

In [ ]:
arr = np.dstack((arr1, arr2))
print(arr)
print("2-D array stack along depth")
arr = np.dstack((arr_1, arr_2))
print(arr)

print()

first_arr3 = np.array([[[1, 2, 3], [4, 5, 7]], [[8, 9, 10], [11, 12, 13]]])
second_arr3 = np.array([[[14, 15, 16], [17, 18, 19]], [[20, 21, 22], [23, 24, 25]]])

print("3-d array stack along depth")
arr = np.array((first_arr3, second_arr3))
print(arr)

[[[1 4]
  [2 5]
  [3 7]]]
2-D array stack along depth
[[[ 1  8]
  [ 2  9]
  [ 3 10]]

 [[ 4 11]
  [ 5 12]
  [ 7 13]]]

3-d array stack along depth
[[[[ 1  2  3]
   [ 4  5  7]]

  [[ 8  9 10]
   [11 12 13]]]


 [[[14 15 16]
   [17 18 19]]

  [[20 21 22]
   [23 24 25]]]]
