<a href="https://colab.research.google.com/github/MANOJKUMARKONDURU/3_NumPy_Oct_2025/blob/main/3_Array_slicing_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

#Slicing arrays
Means taking elements from one given index to another given index

* we can slice an array like this -  **arr[start:end]**
* we can also add a step - **arr[start: end:step]**

* if you don't pass start its considered as **0**
* if you don't pass end its considered length of array in that dimension

*  if we don't pass step its considered as **1**

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 7])
print(arr[0:3])
print(arr[:5])
print(arr[3:])
print(arr[:])
print(arr[0:5:2])

print(arr[-3: -1])

[1 2 3]
[1 2 3 4 5]
[4 5 7]
[1 2 3 4 5 7]
[1 3 5]
[4 5]


#Slicing 2-D array

**arr[rows:rows, column_index]**

In [ ]:
arr = np.array( [[1, 2, 3, 12, 15, 21], [4, 5, 7, 13, 27, 25]] )#, [[8, 9, 10], [11, 12, 13]]])

print(arr[1, 1:4 ])

print(arr[0:2, 2]) # get index 2 from both elements

print(arr[0:2, 1:4]) #slice index 1 to 4 from the both elements

[ 5  7 13]
[3 7]
[[ 2  3 12]
 [ 5  7 13]]


#3-D Array slicing

**arr[rows:rows, which part, start: end]**

In [ ]:
import numpy as np
arr = np.array([
    [[1, 2, 3, 12, 15, 21, 32], [4, 5, 7, 13, 27, 25, 33]],
    [[8, 9, 10, 57, 77, 70, 71], [11, 12, 13, 28, 75, 35, 212]]
    ])
print(arr)
print(arr[0, 0, 2])
print(arr[1, 1, : 4])

#arr[rows:rows, which part, start: end]
print(arr[0:2, 1, 3:6])


[[[  1   2   3  12  15  21  32]
  [  4   5   7  13  27  25  33]]

 [[  8   9  10  57  77  70  71]
  [ 11  12  13  28  75  35 212]]]
3
[11 12 13 28]
[[13 27 25]
 [28 75 35]]
