<a href="https://colab.research.google.com/github/MANOJKUMARKONDURU/3_NumPy_Oct_2025/blob/main/02_NumPy%20Random%20-%20October02_2025%20-%20oct04_2025/02_Random_Data_Distribution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# What is Data Distribution?

Data ditribution is a list of all possible values, and how often each value occurs.

Such lists are important when working with statistics

#Random Distribution

A random distribution is a set of random numbers that follow a certain **probability denstiy function**.

**Pobability Density Function**: A function that describes a continuous pobability . i.e. probabilty of all values in an array.

We can generate random numbers based on defined probabilities using the **choice()** method of the **random** module


The Probability is set by the number between 0 and 1 , where  "0 means that the value will never occur" and "1 means that the value will always occurss."

In [ ]:
from numpy import random


Generate a 1-d array containing 100 values, where each value has 3, 4, 5, or 9



In [ ]:
x = random.choice([3, 5, 7, 9], p = [0.3, 0.3, 0.4, 0.0], size = (100))
print(x)



[3 7 7 5 7 3 7 5 3 7 5 5 5 7 3 5 7 5 7 7 3 5 3 3 3 7 5 5 7 5 3 5 3 5 5 7 3
 3 5 5 7 7 3 7 7 5 5 7 5 7 7 7 7 7 5 5 3 5 5 5 3 5 7 3 3 5 5 7 5 3 7 7 7 3
 7 5 5 7 7 5 5 7 7 5 3 5 5 5 5 5 3 5 5 7 7 3 7 5 3 7]


#The sum of all the probability numbers should be 1

In [ ]:
#2-D array with 3 rows each containing 5 values

x = random.choice([3, 5, 7, 4], p = [0.2, 0.3, 0.5, 0.0], size = (3, 5))
print(x)


print("\n3-D array")
x = random.choice([3, 5, 7, 4], p = [0.2, 0.3, 0.5, 0.0], size = (3, 5, 2))
print(x)

[[3 3 5 5 7]
 [7 3 7 3 7]
 [5 3 7 5 3]]

3-D array
[[[7 7]
  [7 3]
  [5 3]
  [5 3]
  [3 7]]

 [[5 3]
  [7 7]
  [7 7]
  [7 7]
  [7 7]]

 [[7 7]
  [7 7]
  [5 7]
  [3 7]
  [5 3]]]
