<a href="https://colab.research.google.com/github/MANOJKUMARKONDURU/3_NumPy_Oct_2025/blob/main/02_NumPy%20Random%20-%20October02_2025%20-%20oct04_2025/01_Random_Numbers_in_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#What is a Random Number?

Random number does **not** mean different number every time. Random number means which cannot be predicted Logically.

#Pseudo Random and True Random

Computers work on programs, and programs are definitive set of instructions. So there should be some algorithm to generate a random number as well.

**If there is a program to generate random number that can be predicted, thus its not a random number**

Random numbers generated through generation algorithm are called **pseudo random**

**Can we make truly random numbers? - Yes**

Yes. In order to generate truly random on our computers we need to get the random data from some outside source. This outside source is generally our keystrokes, mouse movements, data on network etc.

**We don't need truly random numbers, unless it is realated to security(eg: encryption keys)**

now we are going to see the usage of **pseudo random numbers**

#Generate Random Number

NumPy offers the **random** module to work with randdom numbers.

In [ ]:
from numpy import random

In [ ]:
# Generate Random integer from 0 to 100

x = random.randint(100)
print(x)

14


# Generate Random Float

the random module's **rand()** method returns a random float between 0 and 1.


In [ ]:
x = random.rand()
print(x)

0.9597863969077652


# Generate Randoom Array
You can use the two methods from the above examples to make random arrays.
#Integers
The **randint()** method takes a **size** parameter where you can specify the shape of an array.


In [ ]:
x = random.randint(15, size = (3))  # size = (how many elemnts)
print(x)
print()

x = random.randint(100, size = (3, 5))  #size = (how many rows, how many columns)
print(x)

print("3-D array")
x = random.randint(100, size = (2, 3, 5)) #size = (dimensions, rows, columns)
print(x)

[14  9 14]

[[47 74 74 94 80]
 [56 53  0 21  1]
 [34 34 74 27 74]]
3-D array
[[[98 57 40 72 76]
  [31 62 78 66 99]
  [88 97 98 23 30]]

 [[95 86 53 54 20]
  [32 84 94 96 92]
  [82 54 88 94  5]]]


# Float

The **rand()** method allows to specify the shape of the array






In [ ]:
x = random.rand(5)
print(x)

print("\n2-D array with rand()")
x = random.rand(3, 3)
print(x)
print("\n3-d array with rand()")
x = random.rand(2, 3, 5)
print(x)

[0.03348692 0.52810843 0.57859609 0.5097444  0.18694845]

2-D array with rand()
[[0.28463672 0.35181783 0.32710246]
 [0.80917558 0.56313628 0.05530104]
 [0.68689595 0.94419859 0.22253725]]

3-d array with rand()
[[[0.57284228 0.759427   0.8934374  0.72128928 0.75111139]
  [0.83330208 0.03474069 0.30078215 0.85912663 0.3471029 ]
  [0.10413405 0.10319029 0.62235797 0.41175377 0.28844574]]

 [[0.03385052 0.71037595 0.66571737 0.85832853 0.59428918]
  [0.7718349  0.46697455 0.01598634 0.56826144 0.5803347 ]
  [0.50980565 0.8564864  0.72854468 0.45977332 0.27759018]]]


# Generate Random number from an Array

The **choice()** method allows to generate a random number based on the array of values.

It takes array as a parameter and randomly returns one of the values.

To print specified number of values or shape of the array we can use **size**

In [ ]:
x = random.choice([1, 2, 3, 4, 5])
print(x)

print("\n2-D Array")
x = random.choice([1, 2, 3, 4, 5], size = (3, 5))
print(x)

print("\n3-d Array")
x = random.choice([1, 2, 3, 4, 5], size = (2, 3, 5))
print(x)

1

2-D Array
[[5 3 4 2 5]
 [2 2 1 3 4]
 [2 2 1 5 4]]

3-d Array
[[[1 2 1 5 5]
  [1 5 5 4 5]
  [1 4 5 5 5]]

 [[5 1 4 4 3]
  [4 1 4 1 4]
  [5 5 5 1 4]]]
