<a href="https://colab.research.google.com/github/MANOJKUMARKONDURU/3_NumPy_Oct_2025/blob/main/1_Numpy_Bascis_Oct1_2025/7_Array_Reshaping_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Reshaping Arrays

Means changing the shape of the array with **reshape()**.

By reshaping we can add or remove dimensions or change the number of elements in each dimension.
---
#Reshape From 1-D to 2-D, 1-D to 3-D

In [ ]:
import numpy as np


In [ ]:
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])

arr2 = arr1.reshape(2, 4)
arr3 = arr1.reshape(2, 2, 2)
print(arr2)
print()
print(arr3)

[[1 2 3 4]
 [5 6 7 8]]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#Reshape results view

In [ ]:
print(arr2.base)

print(arr3.base)

[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]


#Unknown Dimension

Allowed to have one "Unknown dimension"


Pass **-1** as the value and NumPy will calculate for you

In [ ]:
new_arr = arr1.reshape(2, 2, -1)
print(new_arr)
print()

new_arr2 = arr2.reshape(-1, 2, 2)
print(new_arr2)
print()
new_arr3 = new_arr2.reshape(2, -1)
print(new_arr3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

[[1 2 3 4]
 [5 6 7 8]]


#Flattening the Arras
Means converting a multidimensional array into 1-D array

we can use **reshape(-1) to do this

In [ ]:
new_arr1 = new_arr3.reshape(-1)
print(new_arr1)

[1 2 3 4 5 6 7 8]


In [ ]:
7

Note: There are a lot of functions for changing the shapes of arrays in numpy flatten, ravel and also for rearranging the elements rot90, flip, fliplr, flipud etc. These fall under Intermediate to Advanced section of numpy.