<a href="https://colab.research.google.com/github/MANOJKUMARKONDURU/3_NumPy_Oct_2025/blob/main/1_Numpy_Bascis_Oct1_2025/11_Seaching_Arrays_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Searching Arrays

You can search an array for a certain value and return the indexes that get a match

To search an array, use the **where()** method.

In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([1, 2, 3, 7, 7, 5])

arr = np.where(arr1 == 7)

print(arr)  # value 7 is present at 3, 4.

(array([3, 4]),)


Find the indexes where the values are even and odd


In [ ]:
arr1 = np.array([1, 2, 3, 7, 7, 5, 8, 10, 12])

arr = np.where(arr1 % 2 == 0)

print(arr)

arr = np.where(arr1 % 2 == 1)
print(arr)

(array([1, 6, 7, 8]),)
(array([0, 2, 3, 4, 5]),)


# Search Sorted
**searchsorted()** which performs a binary search in the array, and the returns the index where the specified value would be inserted to maintain the search order


The **searchsorted()** method is assumed to be used on sorted arrays

In [ ]:
arr1 = np.array([1, 4, 7, 10])

arr = np.searchsorted(arr1, 7)
print(arr)

2


#Search from the Right Side
By default left most index is returned but we can give **side = 'right'** to return the right most index insted


In [ ]:
arr1 = np.array([1, 4, 7, 7, 10])

arr = np.searchsorted(arr1, 7, side = 'right')
print(arr)

4


#Mulltiple values

To search for more than one value, use an array with the specified value


The return value is an array for the following example : [1, 1, 4] containing three indexes where 2, 3, 8 would be inserted in the original array to maintain the order.

In [ ]:
arr = np.searchsorted(arr1, [2, 3, 8])
print(arr)

[1 1 4]
