
NumPy is a Python library

NumPy is used for  working with arrays

Numpy is short for "Numerical Python"

NumPy was created in **2005 by Travis Oliphant**.

#**ndarray** --- **N-dimensional** array object in NumPy
A **dimension** in arrays is one level of array depth(nested arrays)  
1 - D Like a list  
2 - D like a matrix  
3 - D like a cube ... so on

Array means collecction of items(usually numbers) stored in grid-like structure   
**All elements must be same data type**   
It has attributes like


*   .ndim - number of dimensions
*   .nshape - size along each dimension
*   .dtype - data type of an element



---





# Why NumPy faster than Lists?
NumPy arrays are stored in one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.


This behaviour is called locality of reference in computer science.



In [ ]:
import numpy
arr = numpy.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


In [ ]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [ ]:
print(np.__version__)

2.0.2


In [ ]:
#type() - tells the type of the object passed to it

print(type(arr))

<class 'numpy.ndarray'>


To create an **ndarray**, we can pass a list, tuple or any array - like object into the **array()** methond , then it will be converted into an **ndarray**

In [ ]:
arr = np.array((1, 2, 4))
print(arr)

[1 2 4]


#0-D Arrays
Each value in an array is a 0-D array(scalar)


In [ ]:
arr = np.array(21)
print(arr)

21


#

#1-D Arrays
An array that has 0-D arrays as it's elements is called 1-D array


In [ ]:
arr = np.array([1, 2, 3, 4, 7])
print(arr)


[1 2 3 4 7]


#2-D Arrays
An array that has 1-D arrays as it's elements is called 2-D array

Often used to represent matrix

**Arrays that have rows and columns**

**Shape -  [row],[column]

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 7]])

print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 7]]
2


In [ ]:
arr = np.array([ [1, 2], [2, 3], [4, 5]])

print(arr)
print(arr.ndim)

[[1 2]
 [2 3]
 [4 5]]
2


#3-D Arrays
An array that has 2-D(matrices) as it's elements called 3-D array

**Arrays that have depth, rows, columns**

**Shape - [deptth][row][column]






In [ ]:
arr = np.array([
     [
        [1], [2]
    ],
    [
        [3], [4]
    ]
])
print(arr)
print(arr.ndim)

[[[1]
  [2]]

 [[3]
  [4]]]
3


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 7]],[[1, 4, 7], [2, 3, 7]]])
print(arr)

print(arr.ndim)

[[[1 2 3]
  [4 5 7]]

 [[1 4 7]
  [2 3 7]]]
3


#Higher dimensions

An array can have any number of dimensions

You can define the number of dimensions by using **ndmin**








In [ ]:
arr = np.array([1,2, 3, 4, 5], ndmin = 5)
print(arr)
print(arr.ndim)

[[[[[1 2 3 4 5]]]]]
5
