In [1]:
print("JESUS")

JESUS


# Searching Arrays

You can search an array for a certain value and return the indexes that get a match

To search an array, use the **where()** method.

In [2]:
import numpy as np

In [5]:
arr1 = np.array([1, 2, 3, 7, 7, 5])

arr = np.where(arr1 == 7)

print(arr)  # value 7 is present at 3, 4.

(array([3, 4]),)


Find the indexes where the values are even and odd


In [7]:
arr1 = np.array([1, 2, 3, 7, 7, 5, 8, 10, 12])

arr = np.where(arr1 % 2 == 0)

print(arr)

arr = np.where(arr1 % 2 == 1)
print(arr)

(array([1, 6, 7, 8]),)
(array([0, 2, 3, 4, 5]),)


# Search Sorted
**searchsorted()** which performs a binary search in the array, and the returns the index where the specified value would be inserted to maintain the search order


The **searchsorted()** method is assumed to be used on sorted arrays

In [16]:
arr1 = np.array([1, 4, 7, 10])

arr = np.searchsorted(arr1, 7)
print(arr)

2


#Search from the Right Side
By default left most index is returned but we can give **side = 'right'** to return the right most index insted


In [20]:
arr1 = np.array([1, 4, 7, 7, 10])

arr = np.searchsorted(arr1, 7, side = 'right')
print(arr)

4


#Mulltiple values

To search for more than one value, use an array with the specified value


The return value is an array for the following example : [1, 1, 4] containing three indexes where 2, 3, 8 would be inserted in the original array to maintain the order.

In [23]:
arr = np.searchsorted(arr1, [2, 3, 8])
print(arr)

[1 1 4]
