In [1]:
print("JESUS")

JESUS


#Sorting Arrays  - **sort()**

Sorting means putting elements in an ordered sequence

Ordered sequence means its any sequence of order corresponding to elements, like numeric or aplabetical, ascending or descending.

The NumPy ndarray object has a funcion called **sort()**, that will sort a specified array.


In [2]:
import numpy as np

In [3]:
arr1 = np.array([1, 2, 5, 4, 7, 3])
arr = np.sort(arr1)
print(arr)

[1 2 3 4 5 7]


**This method return a copy of the array, leaving the original array unnchanged**

You can also sort arrays of strings or any other dara types

In [4]:
arr_string = np.array(["Mango", "Lambo", "Mustang"])

print(np.sort(arr_string))

['Lambo' 'Mango' 'Mustang']


#sort a boolean array

In [6]:
boolean_arr = np.array([True, False, False, True])

print(np.sort(boolean_arr))

[False False  True  True]


#Sorting a 2-D Array
Both arrays will be sorted

In [7]:
arr = np.array([[3, 2, 1], [7, 5, 4]])
print(np.sort(arr))

[[1 2 3]
 [4 5 7]]


# Sortin 3-D array




In [9]:
arr3 = np.array([[[1, 21, 2], [7, 3, 5]], [[27, 17, 15], [100, 97, 77]]])

print(np.sort(arr3))

[[[  1   2  21]
  [  3   5   7]]

 [[ 15  17  27]
  [ 77  97 100]]]
