#Difference between **copy** and **View**

**Copy** - copy is new array

**View** - just a view of the original array
---
#copy()
The copy() should not be affected by the changes made to the original

and

The original should not be affected by the changes made to the  copy()



In [ ]:
import numpy as np


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 21
x[0] = 27
print(arr)
print(x)

[21  2  3  4  5]
[27  2  3  4  5]


#**view()**
#Make changes in view
The view should be affected by the changes made to original array

#

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.view()
arr[0] = 21

print(arr)
print(x)

[21  2  3  4  5]
[21  2  3  4  5]


#Make changes in view
The original array should be affected by the changes made to  view

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.view()
x[4] = 51

print(arr)
print(x)

[ 1  2  3  4 51]
[ 1  2  3  4 51]


#Check if Array owns its Data
copy - owns data

view - doesn't own data


To check this...
Every numPy array has the attribute **base** that return **None** if the arras owns the data

Otherwise, **base** attribute reffers to original array

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

new_copy = arr.copy()
new_view = arr. view()

print(new_copy.base)  # copy returns None
print(new_view.base) # View retrns the original array

None
[1 2 3 4 5]
