In [1]:
print("JESUS")

JESUS


#Iterating Arrays

Means going through elements one by one

with basic **for** loop we can iterate through the elements

---
#Iterating through 1-D array

In [2]:
import numpy as np


In [3]:
arr = np.array([1, 2, 3, 14, 5])
for x in arr:
  print(x)


1
2
3
14
5


#Iterating through 2-D array

It will go through all the rows
**If we iterate through n-D array it will go through n-1th dimension one by one**



In [4]:
arr2 = np.array([[1, 2, 3, 4], [5, 7, 8, 10]])

for x in arr2:
    print(x)


for x in arr2:   #Traverse through array rows
  for y in x: # Traverse through array columns
    print(y)

[1 2 3 4]
[ 5  7  8 10]
1
2
3
4
5
7
8
10


#Iterating 3-D array
It will go through all the 2-D arrays

In [5]:
arr3 = np.array([[ [1, 2, 3], [4, 5, 7]], [[8, 9, 10], [11, 12, 13]]])

for x in arr3:
  for y in x:
    print(y)
print()

for x in arr3:    #traverse through the  dimensions
  for y in x:   # Traverse through the rows
    for z in y: # Traverse through the columns
      print(z)

[1 2 3]
[4 5 7]
[ 8  9 10]
[11 12 13]

1
2
3
4
5
7
8
9
10
11
12
13


# Iterating Arrays Using **nditer()**

It difficult to go through every element of an array by using **for** loop for arrays with higher dimensionality.

But with the function **nditer()** we can perfrom basic to very advanced iterationd.

In [6]:
for x in np.nditer(arr3):
  print(x)

print()
for x in np.nditer(arr3[0:1]):
  print(x)

1
2
3
4
5
7
8
9
10
11
12
13

1
2
3
4
5
7


#Iterating Array with different datatypes

We can use **op_datatyppes** arugument and pass its expected datatype to change the datatype of elements while iterating
Numpy cannot change the type of the elements in-place(where the element is in array), so it needs other space to perform this, that extra space is called buffer, and in order to enable it in **nditer()** we pass **flags = ['buffered']**

In [7]:
for x in np.nditer(arr3, flags = ['buffered'], op_dtypes = ['S'] ):
  print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'5')
np.bytes_(b'7')
np.bytes_(b'8')
np.bytes_(b'9')
np.bytes_(b'10')
np.bytes_(b'11')
np.bytes_(b'12')
np.bytes_(b'13')


#Using **dtype = object** for Mixed datatypes
This is the simplest way to store and iterate through diferent types of datatypes.

In [8]:
mixed_array = np.array(["Manoj", 1, 2, 4.5], dtype = object)

for x in mixed_array:
  print(x)

Manoj
1
2
4.5


#Iterate through different step size



In [9]:
for x in np.nditer(arr3[ : , ::2]):
  print(x)

1
2
3
8
9
10


In [13]:
arr3 = np.array([[ [1, 2, 3], [4, 5, 7]], [[8, 9, 10], [11, 12, 13]]])
sliced = arr3[ : , ::2]    # slice with step 2 along the last axis(columns)
#[]
for x in np.nditer(sliced):
  print(x)

1
2
3
8
9
10


In [14]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):   # slice with step 2 along the last axis(columns)
  print(x)

1
3
5
7


# Enumerated Iteration Using **ndeumerate()**
Enumeration means mentioning sequence number of somethings one by one.


If we want to corresponding index of  the element while iterating, the **ndenumerate()** in those usecases


In [17]:
arr1 = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr1):
  print(idx, x)
print()
arr2 = np.array([[1, 2, 3], [4, 5, 7]])

for idx, i in np.ndenumerate(arr2):
  print(idx, i)

(0,) 1
(1,) 2
(2,) 3

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 7
