<a href="https://colab.research.google.com/github/MANOJKUMARKONDURU/3_NumPy_Oct_2025/blob/main/03_NumPy%20ufuncs%20-%20oct04%20-%20oct06_2025/03_Simple_Arithmetic_ufunc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Simple Arithmetic
You could use arithmetic operators + - * / directly between NumPy arrays, but this section discusses an extension of the same where we have functions that can take any array-like objects e.g. lists, tuples etc. and perform arithmetic conditionally.


**Arithmetic Conditionally**: means that we can define conditions where the arithmetic operations should happen.

All of the dicussed arithmetic functions take a **where** parameter in which we can specify that condition.

In [ ]:
import numpy as np

#add()

In [ ]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,9,8,7,6])

added_arr =np.add(arr1, arr2)
print(added_arr)

[11 11 11 11 11]


#subtract()

In [ ]:
subtracted_arr = np.subtract(arr1, arr2)
print(subtracted_arr)

[-9 -7 -5 -3 -1]


#mutiply()

In [ ]:
multiplied_arr = np.multiply(arr1, arr2)
print(multiplied_arr)


[10 18 24 28 30]


#divide()

In [ ]:
divided_arr = np.divide(arr1, arr2)
print(divided_arr)

[0.1        0.22222222 0.375      0.57142857 0.83333333]


#powe()
rises the values from the first array to the power of the values of the second array.

In [ ]:
power_arr = np.power(arr1, arr2)
print(power_arr)


[    1   512  6561 16384 15625]


#Remainder - mod(), reminder()


In [ ]:
mod_arr = np.mod(arr1, arr2)
remainder_arr = np.remainder(arr1, arr2)

print(mod_arr)
print(remainder_arr)

[1 2 3 4 5]
[1 2 3 4 5]


#Quotient and Mod - **divmod()**
return both the quotient and mod. The return value is two arrays, the **first array contains the quotients** and the **second array contains the mod**.



In [ ]:
divmod_arr = np.divmod(arr1, arr2)
print(divmod_arr)

(array([0, 0, 0, 0, 0]), array([1, 2, 3, 4, 5]))


#Absolute values - absolute(), abs()

Both do the same absolute operation element wise but we should use the **absolute()** to avoid confusion with python's inbuilt **maths.abs()

In [ ]:
arr = np.array([-1, -2, 3, -4, -5])
absolute_arr = np.absolute(arr)
abs_arr = np.abs(arr)
print(absolute_arr)
print(abs_arr)

[1 2 3 4 5]
[1 2 3 4 5]
