<a href="https://colab.research.google.com/github/MANOJKUMARKONDURU/3_NumPy_Oct_2025/blob/main/03_NumPy%20ufuncs%20-%20oct04%20-%20oct06_2025/04_Rounding_decimals_ufunc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Rounding Decimals
There are primarily **Five** ways of rounding off the decimals in NumPy.
1. truncation - trunc()
2. fix - fix()
3. rounding - around()
4. floor - floor()
5. Ceil - ceil()

In [ ]:
import numpy as np

# Truncation, Fix - **trunc(), fix()**
Remove the decimals, and return the float number closest to the zero. Use the **trunc()** and **fix()** functions.


Will make the decimals as zero.

In [ ]:
arr = np.trunc( [-3.977, 3.1777] )
print(arr)


arr = np.fix( [-3.777, 3.1777] )
print(arr)

[-3.  3.]
[-3.  3.]


#Rounding - **around()**
The **around()** function rounds each element in an NumPy array to a specified number of decimal places.

#syntax
np.around(a, decimals = 0, out = None)
*  a = the input array
*  decimals = 0- round to the nearest integer. 2- round to two decimal places, -1 - round to nearest ten

* out = optional array to store the result



In [ ]:
#round to the nearest integer
arr = np.around([1.2, 2.47, 2.5, 2.51, 2.6])
print(f"round to the nearest integer: {arr}")

#round to two decimal places
arr = np.around([1.2, 2.47877, 2.5, 2.51, 2.677777], 2)
print(arr)

#Round to nearest Ten(Negative Decimal)
arr = np.around([11.2, 12.47877, 15.5, 22.51, 12.677777], -1)
print(arr)

round to the nearest integer: [1. 2. 2. 3. 3.]
[1.2  2.48 2.5  2.51 2.68]
[10. 10. 20. 20. 10.]


#Floor - floor()
The **floor()** function rounds the decimal to **nearest lower integer**.


In [ ]:
arr = np.floor([1.2, 2.47, 2.5, 2.51, 2.9])
print(arr)


[1. 2. 2. 2. 2.]


#Ceil - ceil()
The **ceil()** function rounds off the decimal to the **nearest upper integer**.

In [ ]:
arr = np.ceil([1.2, 3.57, 4.9])
print(arr)

[2. 4. 5.]
