<a href="https://colab.research.google.com/github/MANOJKUMARKONDURU/3_NumPy_Oct_2025/blob/main/03_NumPy%20ufuncs%20-%20oct04%20-%20oct06_2025/11_Trigonometric_Fuctions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Trigonometric Functions

NumPy provides the ufuncs **sin()**, **cos()** and **tan()** that take values the values in radians and produce the corresponding sin, cos and tan values.

In [ ]:
import numpy as np

In [ ]:
x = np.sin(np.pi/2)
print(x)

1.0


In [ ]:
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
x = np.sin(arr)
print(x)

[1.         0.8660254  0.70710678 0.58778525]


#Convert Degrees into Radians
What Is a Radian?

A radian is the angle created when the length of an arc equals the radius of the circle. So:

*   If you wrap the radius of a circle around its edge, the angle that arc makes at the center is 1 radian.

*   A full circle is 2π radians, which equals 360 degrees.


By default all of the trigonometric functions take radians aas paremeters but we can convert radians to degrees and vice versa as well in NumPy


**Note**: Radians values are pi/180*degree_values.




#Degree to Radians

In [ ]:
arr = np.array([90, 180, 270, 360])
x = np.deg2rad(arr)
print(x)

[1.57079633 3.14159265 4.71238898 6.28318531]


#Radians to Degrees


In [ ]:
arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi, np.pi/4])
x = np.rad2deg(arr)
print(x)

[ 90. 180. 270. 360.  45.]


#Finding Angles
Finding angles from values of sine,cos, tan.  E.g: sin, cos and tan inverse(arcsin, arccros, arctan)

NumPy provides ufuncs **arcsin(), arccos()** and **arctan()** that **produce radian values** for corresponding sin, cos, tan values give.


In [ ]:
x = np.arcsin(1.0)
print(x)

x = np.arccos(1.0)
print(x)

x = np.arctan(1.0)
print(x)

1.5707963267948966
0.0
0.7853981633974483


#Angles of each values in an Array


In [ ]:
arr = np.array([1, -1, 0.1])
x = np.arcsin(arr)

print(x)

[ 1.57079633 -1.57079633  0.10016742]


#Hypotenues
Finding Hypotenus using pythagoras theorem in Numpy.

*    (Hypotenuse) ** 2 = (Base) ** 2 + (height) ** 2

NumPy provides the **hypot()** function that takes the base and perpendicular(height) values and produces the Hypotenuse based on Pythagoras theorem.

In [ ]:
base = 3
height = 4
x = np.hypot(base, height)
print(x)

5.0
