<a href="https://colab.research.google.com/github/MANOJKUMARKONDURU/3_NumPy_Oct_2025/blob/main/03_NumPy%20ufuncs%20-%20oct04%20-%20oct06_2025/13_Set_Operations_ufunc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#What is a set?
A set in mathematics is a collection of unique elements.

Sets are used for operations involving frequent intersection, unionn and difference operarions.

---
#Create sets in Numpy
We can use NumPy's **unique()** method to find unique elements from any array.

**Note**: Remember that the sett arrays should only be **1-D arrays**.

#convert the following array with repeated elements to a set:


In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,1,2,2,3,3,4,5,5,6,6])
print(f"Original array: {arr}")
x = np.unique(arr)
print(x)

Original array: [1 1 2 2 3 3 4 5 5 6 6]
[1 2 3 4 5 6]


#Finding Union
To Find the unique values of two arrays, use the **union1d()** method


In [ ]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([3,4,5,6])
newarr = np.union1d(arr1, arr2)
print(newarr)

[1 2 3 4 5 6]


#Finding Intersection
To find only the values that are present in both arrays, use the **intersect1d()** method

In [ ]:
newarr = np.intersect1d(arr1, arr2)
print(newarr)

new = np.intersect1d(arr1, arr2, assume_unique=True)
print(new)

[3 4]
[3 4]


**Note:** the intersect1d() method takes an optional argument assume_unique, which if set to True can speed up computation. It should always be set to True when dealing with sets.

#Finding Difference
To find only the values in the first set that is **NOT present** in the second set, use the **setdiff1d()**method.

In [ ]:
newarr = np.setdiff1d(arr1, arr2, assume_unique = True)
print(newarr)

[1 2]


#Finding Symmetric difference
To find only the values that are **NOT present** in **BOTH** sets, use the **setxor1d()** method.

In [ ]:
set1 = np.array([0,1,2,5,7,8,9])
set2 = np.array([1,2,3,4,5])
newarr = np.setxor1d(set1, set2, assume_unique = True)
print(newarr)

[0 3 4 7 8 9]


In [ ]:
from IPython.display import HTML

HTML("<h1>Hello, Yashaswini!</h1><p>This is HTML inside Colab.</p>")


In [ ]:
html_code = """
<html>
  <body>
    <h2>Dynamic HTML</h2>
    <p>This was generated inside Colab!</p>
  </body>
</html>
"""


from IPython.display import display, HTML
display(HTML(html_code))